["cc-by-sa-4.0"]
name = "CC BY-SA 4.0"
url = "https://creativecommons.org/licenses/by-sa/4.0/deed.zh"

["cc-by-nc-sa-4.0"]
name = "CC BY-NC-SA 4.0"
url = "https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh"

[copyright]
name = "版权所有"

[default]
aliasTo = "copyright"