name: build-and-deploy
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - uses: actions/cache@v3
        with:
          path: ~/.cache
          # An explicit key for restoring and saving the cache
          key: playwright
      - run: pnpm install
      - run: pnpm dlx playwright install
      - run: pnpm build
      - run: pnpm postbuild
      - run: pnpm dlx wrangler pages deploy dist --project-name=blog-leo
        if: github.event_name != 'pull_request'
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
